### ISSUE TITLE
Faux positif lors du check à 5 arg

### ISSUE THREAD

**Issue by hibou42** [tricaducee/Push_Swap_Tester#2]
Bonjour bonjour !
Déjà, merci pour ce testeur qui ma beaucoup aidé.
J'ai run ce tester pour mon push swap avant de rendre le projet, tout était au vert. Mais j'ai quand meme fail le projet ... (c'est que des points d'éval alors osef)
Lors des check pour le tri de 5 argument, le tester dit OK jusqu'à 15 opérations. Cependant, le maximum autorisé par l'évaluation est de 12 opérations ...
Surement utile pour les prochains =)
Bonne continuation et encore merci !!!

**Comment by tricaducee** [comment]
Merci pour ton retour !

Il se peut que le fait que ton Push-Swap n'ait pas passé soit dû aux critères d'évaluation qui ont tendance à être un peu nébuleux. Le testeur calcule des moyennes de tous les résultats, et ce sont ces moyennes qui sont utilisées pour l'évaluation (c'est ainsi que j'ai compris les critères d'évaluation). Cependant, certains pourraient considérer qu'il ne faut pas faire de moyenne mais prendre chaque résultat séparément.

Par exemple, si tu obtiens pour 5 nombres, 10 opérations, 11 opérations et 15 opérations, en moyenne ça fait bien 12, ce qui passe l'évaluation malgré un résultat supérieur. Je pourrais faire une version qui regarde chaque résultat indépendamment, mais je trouve ça assez injuste de mettre faux si la moyenne est bonne.
Je vais voir si j'ai le temps de rajouter une option pour les résultats indépendants les uns des autres. En attendant, tu peux regarder les résultats un par un.

Je suis désolé que ton Push-Swap n'ait pas passé.
Bonne chance pour le prochain push !!!

**Comment by hibou42** [comment]
Bien entendu, je ne remet pas la faute de mon echec sur ton testeur ! Mais dans l'eval il est bien noté MAX 12 opérations, pas moyenne de 12 sur toutes les possibilités ...
Ton testeur m'a beaucoup aider pour rapidement tester mon code et je t'en remercie beaucoup !

**Comment by tricaducee** [comment]
Merci !

J'ai pris en compte ton commentaire, et je viens de mettre à jour le script. Il affiche désormais les moins bons scores, et le nombre de points obtenus pour ces scores en plus de la moyenne. Si jamais il y a encore un problème, fais-moi signe !
Je clos l'issue.
